language: php

install:
  - composer require seld/jsonlint
  - composer require justinrainbow/json-schema

script:
  - for f in draft-*/*; do vendor/bin/jsonlint $f; done
  - vendor/bin/validate-json draft-00/measurement.ogrp draft-00/schema
  - vendor/bin/validate-json draft-01/measurement.ogrp draft-01/schema
