language: php

install:
  - composer require seld/jsonlint

before_script:
  - wget https://github.com/neilpa/yajsv/releases/download/v1.3.0/yajsv.linux.amd64 -O validate-json
  - chmod a+x validate-json
  - export PATH=$PATH:$PWD

script:
  - for f in draft-*/*; do vendor/bin/jsonlint $f; done
  - validate-json -s draft-00/schema draft-00/measurement.ogrp
  - validate-json -s draft-01/schema draft-01/measurement.ogrp
